version: 2.1
jobs:
  # Install dependencies and run tests
  build-and-test:
    docker:
      - image: circleci/node:12.15.0-stretch
    steps:
      - checkout
      - run: npm ci
      - run: npm test

# Build a Docker image and push to Docker Hub
# Authenticate with Digital Ocean CLI and deploy the app
deploy:
  docker:
    - image: circleci/node:12.15.0-stretch
  steps:
    - checkout
    # Allow using Docker commands
    - setup_remote_docker
    - run: bash deploy.sh
