version: 2.1
jobs:
  # Install dependencies and run tests
  build-and-test:
    docker:
      - image: circleci/node:12.15.0-stretch
    steps:
      - checkout
      - run: npm ci
      #- run: npm test

  # Build a Docker image and push to Docker Hub
  # Authenticate with Digital Ocean CLI and deploy the app
  deploy:
    docker:
      - image: circleci/node:12.15.0-stretch
        auth:
          username: redwizardofoz
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      # Allow using Docker commands
      - setup_remote_docker
      # Build the JAR file
      - run: mvn clean package # or ./gradlew build if using Gradle
      # Build the Docker image
      - run: docker build -t myapp .
      - run: bash deploy.sh

server:
  port: 8080

workflows:
  version: 2
  # Workflow name
  build-deploy:
    jobs:
      - build-and-test
      - deploy:
          requires:
            # Run after all tests have passed
            - build-and-test
