
#version: 2.1
#
#jobs:
#  # Install dependencies and run tests
#  build-and-test:
#    docker:
#      - image: maven:3.6.3-openjdk-17
#    steps:
#      - checkout
#      - run: mvn clean package
#      - run: test -f target/test-0.0.1-SNAPSHOT.jar
#      - persist_to_workspace:
#          root: target/
#          paths:
#            - test-0.0.1-SNAPSHOT.jar
#      - run: cp target/test-0.0.1-SNAPSHOT.jar ./test-0.0.1-SNAPSHOT.jar
#      - run: ls -al target
#
#
#  # Build a Docker image and push to Docker Hub
#  # Authenticate with Digital Ocean CLI and deploy the app
#  deploy:
#    docker:
#      - image: circleci/node:12.15.0-stretch
#        auth:
#          username: redwizardofoz
#          password: $DOCKERHUB_PASSWORD
#    steps:
#      - checkout
#      # Allow using Docker commands
#      - setup_remote_docker
#      - run: bash ./deploy.sh
#server:
#  port: 8080
#
#workflows:
#  version: 2
#  # Workflow name
#  build-deploy:
#    jobs:
#      - build-and-test
#      - deploy:
#          requires:
#            # Run after all tests have passed
#            - build-and-test



version: 2.1

jobs:
  build:
    docker:
      - image: maven:3.6.3-openjdk-17
    working_directory: ~/test
    steps:
      - checkout
      - run:
          name: Build JAR
          command: mvn package -DskipTests
  deploy:
        docker:
          - image: cimg/node:20.0.0
            auth:
              username: redwizardofoz
              password: $DOCKERHUB_PASSWORD
        steps:
          - checkout
        # Allow using Docker commands
          - setup_remote_docker
          - run: bash ./deploy.sh
server:
  port: 8080:8080

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master

